### ISSUE TITLE
support ionic

### ISSUE THREAD

**Issue by mrpower55** [WuglyakBolgoink/cordova-plugin-iroot#1]
hi there, i want to add this plugin on my ionic project

but i can't know what is the class of it to set it on providers,

also i can't know what is the function i need to use on ionic

so please help me

thanks

**Comment by sujit77** [comment]
By default, you can import "IRoot" class from "cordova-plugin-iroot\www". 
But in Ionic, this will generate error, "require", "cordova" and "exec" not defined in web version.

Thus, I have conditionaly added this file in index.html (which is only if device is mobile type).
Now more about that logic [here](https://forum.ionicframework.com/t/open-other-app-using-package-id-name/117089/2).

I have customized my **IRoot.js** file to be as below - 

```
window.isRooted = function (successCallback, failureCallback) {
    cordova.exec(successCallback, failureCallback, "IRoot", "isRooted", []);
};
window.isRootedRedBeer = function (successCallback, failureCallback) {
    cordova.exec(successCallback, failureCallback, "IRoot", "isRootedRedBeer", []);
};
```

Now to call `isRooted` function while avoiding compilation errors in web version, I have created another JS file named **rooted-check.js** with required caller functions - 

```
module.exports = {
    isRootedDevice: function(successCallback, errorCallback){
        window.isRooted(successCallback, errorCallback)
    },
    isRootedRedBeerDevice: function(successCallback, errorCallback){
        window.isRootedRedBeer(successCallback, errorCallback)
    },
}
```
Now, to call required functions - 

```
import * as rootedCheck from '../../assets/js/rooted-check';

rootedCheck.isRootedDevice(
  (booleanVal) => {
    // success callback function
    if(booleanVal){
      // this is a rooted device
    }
  },
  (err) => {       
    // error callback function
    // error while checking rooted status
  }
)
```

This works in web as well as in mobile app. I haven't tested yet in web-browser of a mobile device.

There may be better way(s) of doing this, which we will be happy to know about.

**Comment by WuglyakBolgoink** [comment]
Thank you @sujit77 ,

I check it

**Comment by WuglyakBolgoink** [comment]
@sujit77 I fixed in ionic. I need some tests with normal apps. 

lastChanges@progress

**Comment by sujit77** [comment]
@WuglyakBolgoink, have you found better way of importing this plugin into Angular(2 and above) projects? I can test it out too if you can instruct me for that.

You can test it in [Android studio](https://developer.android.com/studio/index.html) using android emulator.
Devices in Android emulator are rooted. So you don't have to search for a rooted Android device.

However, I haven't tested it in iOS device cause it is hard to find jail broken iPhone.

**Comment by WuglyakBolgoink** [comment]
FYI @sujit77 

1) you should add IRoot-Plugin via

```bash
ionic cordova plugin add cordova-plugin-iroot --save
```

2) declare mock-variable

```typescript
declare var IRoot: IRoot;
```

with `IRoot` Type (*.d.ts File you can import too):

```typescript
import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';
```

----

> src/app/app.component.ts

```typescript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { TabsPage } from '../pages/tabs/tabs';
import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';

declare var IRoot: IRoot;

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage: any = TabsPage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform
      .ready()
      .then(() => {
        // Okay, so the platform is ready and our plugins are available.
        // Here you can do any higher level native things you might need.
        statusBar.styleDefault();
        splashScreen.hide();

        console.log('platform', platform);

        if (platform.is('cordova')) {
          console.log('is cordova');

          try {
            console.log(' IRoot', IRoot);

            IRoot.isRooted((booleanVal) => {
              console.log('IRoot.isRooted success: ', booleanVal);
            }, (err) => {
              console.log('IRoot.isRooted error:', err);
            });
          }
          catch (e) {
            console.log('Error:', e);
          }
        } else {
          console.log('is not cordova');
        }
      });
  }
}
```

----

and build app

![image](https://user-images.githubusercontent.com/2271337/36833702-9b3d252a-1d30-11e8-843f-47c1e100ccf3.png)

`IRoot` is in global scope and you should not import this file.

----

Tested:
* ionic v3.19.1
* cordova v6.5.0
* cordova-plugin-iroot v0.6.0

**Comment by WuglyakBolgoink** [comment]
Hi @mrpower55  & @sujit77 please check if all work with 0.6.1 version

**Comment by sujit77** [comment]
I am not able to make it work. Will you be able to help me in detecting steps which I have missed?

I have installed latest package using - 
```
ionic cordova plugin add cordova-plugin-iroot@latest
```

Trying to import `IRoot` using following - 
```
import { IRoot } from 'cordova-plugin-iroot/iroot'; // Error - Cannot find module "cordova-plugin-iroot/iroot

import { IRoot } from 'cordova-plugin-iroot'; // Error - Cannot find module "cordova-plugin-iroot
```

The one which works is -
```
import { IRoot } from 'cordova-plugin-iroot/www/iroot; 
```
But above one generates error while running - 
```
Runtime Error
Cannot find module "cordova/exec"
```

This is exactly same what I got earlier with version `0.4.0`.

**Comment by WuglyakBolgoink** [comment]
@sujit77 

forgot to import IRoot as cordova plugin.

IRoot Plugin is available as `IRoot`-variable. Noting to do hier.


You can import `iroot.d.ts` for Interface, as I wrote above

**Comment by sujit77** [comment]
@WuglyakBolgoink , new changes works perfectly with pitfalls.

Installed using - `cordova plugin add cordova-plugin-iroot@latest`
```
import { IRoot } from 'cordova-plugin-iroot/iroot';
declare var IRoot: IRoot;
```
I started getting following errors while building package files - 
```
(node:4520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch platform cordova-android@7.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! path C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! code EISGIT
npm ERR! git C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SujitKumarSingh\AppData\Roaming\npm-cache\_logs\2018-03-04T11_02_10_503Z-debug.log
(node:4520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---------------------

(node:372) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch platform cordova-android@7.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! path C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! code EISGIT
npm ERR! git C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SujitKumarSingh\AppData\Roaming\npm-cache\_logs\2018-03-04T11_04_14_350Z-debug.log
(node:372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-------------------------

(node:15856) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch platform cordova-android@7.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! path C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! code EISGIT
npm ERR! git C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\SujitKumarSingh\ProjectApp\node_modules\cordova-plugin-iroot
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SujitKumarSingh\AppData\Roaming\npm-cache\_logs\2018-03-04T11_03_48_224Z-debug.log
(node:15856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**But, finally it worked(I just hibernated system).** 
But, above error message still appear if I reinstall packages after removing `node_modules` and `plugins` folders.

**Comment by sujit77** [comment]
@WuglyakBolgoink **we just need to remove the `.git` folder** which gets created while installing this package. After that everything works perfectly.
 
Look at solutions [[1]](https://github.com/APSL/react-native-version-number/issues/13#issuecomment-341059894), [[2]](https://github.com/shama/napa/issues/53#issuecomment-145899246) with similar issues.

**Comment by WuglyakBolgoink** [comment]
@sujit77  ok. I will check this.

**Comment by CHENPINGFIONA** [comment]
Hi @WuglyakBolgoink,

While I am using the plugin. I am facing the issue of 
Cannot find module "cordova-plugin-iroot/iroot".
How can I resolve this?

Thank you

**Comment by WuglyakBolgoink** [comment]
@CHENPINGFIONA 
you should declare mock-variable. if u need JSDoc, then import interface from `cordova-plugin-iroot/iroot`

see my comment above.

if this do not help you, then how can I reproduce your case?

**Comment by CHENPINGFIONA** [comment]
@WuglyakBolgoink 
I do exactly what your comment shown above. and declared mock-variable. However it still encounter this issue. I just create simple app with the plugin install and added in the codes provided above.

**Comment by WuglyakBolgoink** [comment]
@CHENPINGFIONA can you create a demo repo with your test project to reproduce this error?

**Comment by CHENPINGFIONA** [comment]
@WuglyakBolgoink 
I found out is my typescript version issue. it was 2.3.4, after update to 2.6.2. problem solved.
Really appreciate for your kindly assistance

**Comment by rosstimothy** [comment]
The steps above to compile no longer work

```
❯ ionic info                                                                                                                               

Ionic:

   ionic (Ionic CLI)  : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
```

```
[10:11:33]  typescript: src/app/app.component.ts, line: 8
            Cannot find module '../../plugins/cordova-plugin-iroot/iroot'.

       L8:  import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot'

[10:11:33]  ionic-app-script task: "build"
[10:11:33]  Error: Failed to transpile program
Error: Failed to transpile program
    at new BuildError (~/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at ~/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (~/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile ~/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at ~/node_modules/@ionic/app-scripts/dist/build.js:109:82
[ERROR] An error occurred while running subprocess ionic-app-scripts.
```

**Comment by ng22792** [comment]
> FYI @sujit77
> 
> 1. you should add IRoot-Plugin via
> 
> ```shell
> ionic cordova plugin add cordova-plugin-iroot --save
> ```
> 
> 1. declare mock-variable
> 
> ```ts
> declare var IRoot: IRoot;
> ```
> 
> with `IRoot` Type (*.d.ts File you can import too):
> 
> ```ts
> import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';
> ```
> 
> > src/app/app.component.ts
> 
> ```ts
> import { Component } from '@angular/core';
> import { Platform } from 'ionic-angular';
> import { StatusBar } from '@ionic-native/status-bar';
> import { SplashScreen } from '@ionic-native/splash-screen';
> import { TabsPage } from '../pages/tabs/tabs';
> import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';
> 
> declare var IRoot: IRoot;
> 
> @Component({
>   templateUrl: 'app.html'
> })
> export class MyApp {
>   rootPage: any = TabsPage;
> 
>   constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
>     platform
>       .ready()
>       .then(() => {
>         // Okay, so the platform is ready and our plugins are available.
>         // Here you can do any higher level native things you might need.
>         statusBar.styleDefault();
>         splashScreen.hide();
> 
>         console.log('platform', platform);
> 
>         if (platform.is('cordova')) {
>           console.log('is cordova');
> 
>           try {
>             console.log(' IRoot', IRoot);
> 
>             IRoot.isRooted((booleanVal) => {
>               console.log('IRoot.isRooted success: ', booleanVal);
>             }, (err) => {
>               console.log('IRoot.isRooted error:', err);
>             });
>           }
>           catch (e) {
>             console.log('Error:', e);
>           }
>         } else {
>           console.log('is not cordova');
>         }
>       });
>   }
> }
> ```
> 
> and build app
> 
> ![image](https://user-images.githubusercontent.com/2271337/36833702-9b3d252a-1d30-11e8-843f-47c1e100ccf3.png)
> 
> `IRoot` is in global scope and you should not import this file.
> 
> Test-1:
> 
> * ionic v3.19.1
> * cordova v6.5.0
> * cordova-plugin-iroot v0.6.1
> 
> Test-2:
> 
> * angularJS v1.6.9
> * cordova v6.5.0
> * cordova-plugin-iroot v0.6.1
> 
> Test-3: (todo)
> 
> * angular v4.x
> * cordova v6.5.0
> * cordova-plugin-iroot v0.6.1
> 
> Test-4: (todo)
> 
> * angular v5.x
> * cordova v6.5.0
> * cordova-plugin-iroot v0.6.1





So basically everything worked fine when I removed "import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';" line from the app.component.ts and changed the line "declare var IRoot: IRoot;" to "declare var IRoot;".

Try this and everything works (for people who are trying to directly copy paste the code and getting errors)

Thanks @WuglyakBolgoink for the perfect code !

**Comment by AditioPutra** [comment]
Hi @WuglyakBolgoink 
I got this error
`Cannot find module '../../plugins/cordova-plugin-iroot/iroot'.ts(2307)`
How to fix this?

**Comment by WuglyakBolgoink** [comment]
@AditioPutra but can you find this file manually?

**Comment by AditioPutra** [comment]
> @AditioPutra but can you find this file manually?

no i can't find it

**Comment by WuglyakBolgoink** [comment]
@AditioPutra reinstall plugin and check folder:
![image](https://user-images.githubusercontent.com/2271337/55220515-c1babc00-5207-11e9-93cf-77b355917f44.png)

**Comment by AditioPutra** [comment]
<img width="366" alt="Screen Shot 2019-03-29 at 16 34 30" src="https://user-images.githubusercontent.com/21330110/55223366-9ef8c980-5240-11e9-9bdd-c99dbdb06d62.png">

**Comment by WuglyakBolgoink** [comment]
@AditioPutra 
![image](https://user-images.githubusercontent.com/2271337/55225386-c6d13880-5212-11e9-870c-6eb5c5fa6b06.png)

**Comment by AditioPutra** [comment]
> @AditioPutra
> ![image](https://user-images.githubusercontent.com/2271337/55225386-c6d13880-5212-11e9-870c-6eb5c5fa6b06.png)

index.d.ts

**Comment by mwvarela** [comment]
> @AditioPutra
> ![image](https://user-images.githubusercontent.com/2271337/55225386-c6d13880-5212-11e9-870c-6eb5c5fa6b06.png)

I tried doing types import but it did not work

`import { IRoot } from '../../../plugins/cordova-plugin-iroot/types';`
`File 'd:/app-portal/plugins/cordova-plugin-iroot/types/index.d.ts' is not a module.ts(2306)`

**Comment by mwvarela** [comment]
> @WuglyakBolgoink I tried doing types import in version 0.8.0 but did not work
> `import { IRoot } from '../../../plugins/cordova-plugin-iroot/types';`
> `File 'd:/app-portal/plugins/cordova-plugin-iroot/types/index.d.ts' is not a module.ts(2306)`
>
> on version 0.6.1 `import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';` works

**Comment by mwvarela** [comment]
> > @WuglyakBolgoink I tried doing types import in version 0.8.0 but did not work
> > `import { IRoot } from '../../../plugins/cordova-plugin-iroot/types';`
> > `File 'd:/app-portal/plugins/cordova-plugin-iroot/types/index.d.ts' is not a module.ts(2306)`
> > on version 0.6.1 `import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';` works

**Comment by PraveenFrancis** [comment]
> > FYI @sujit77
> > 
> > 1. you should add IRoot-Plugin via
> > 
> > ```shell
> > ionic cordova plugin add cordova-plugin-iroot --save
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. declare mock-variable
> > 
> > ```ts
> > declare var IRoot: IRoot;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with `IRoot` Type (*.d.ts File you can import too):
> > ```ts
> > import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > src/app/app.component.ts
> > 
> > 
> > ```ts
> > import { Component } from '@angular/core';
> > import { Platform } from 'ionic-angular';
> > import { StatusBar } from '@ionic-native/status-bar';
> > import { SplashScreen } from '@ionic-native/splash-screen';
> > import { TabsPage } from '../pages/tabs/tabs';
> > import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';
> > 
> > declare var IRoot: IRoot;
> > 
> > @Component({
> >   templateUrl: 'app.html'
> > })
> > export class MyApp {
> >   rootPage: any = TabsPage;
> > 
> >   constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
> >     platform
> >       .ready()
> >       .then(() => {
> >         // Okay, so the platform is ready and our plugins are available.
> >         // Here you can do any higher level native things you might need.
> >         statusBar.styleDefault();
> >         splashScreen.hide();
> > 
> >         console.log('platform', platform);
> > 
> >         if (platform.is('cordova')) {
> >           console.log('is cordova');
> > 
> >           try {
> >             console.log(' IRoot', IRoot);
> > 
> >             IRoot.isRooted((booleanVal) => {
> >               console.log('IRoot.isRooted success: ', booleanVal);
> >             }, (err) => {
> >               console.log('IRoot.isRooted error:', err);
> >             });
> >           }
> >           catch (e) {
> >             console.log('Error:', e);
> >           }
> >         } else {
> >           console.log('is not cordova');
> >         }
> >       });
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and build app
> > ![image](https://user-images.githubusercontent.com/2271337/36833702-9b3d252a-1d30-11e8-843f-47c1e100ccf3.png)
> > `IRoot` is in global scope and you should not import this file.
> > Test-1:
> > 
> > * ionic v3.19.1
> > * cordova v6.5.0
> > * cordova-plugin-iroot v0.6.1
> > 
> > Test-2:
> > 
> > * angularJS v1.6.9
> > * cordova v6.5.0
> > * cordova-plugin-iroot v0.6.1
> > 
> > Test-3: (todo)
> > 
> > * angular v4.x
> > * cordova v6.5.0
> > * cordova-plugin-iroot v0.6.1
> > 
> > Test-4: (todo)
> > 
> > * angular v5.x
> > * cordova v6.5.0
> > * cordova-plugin-iroot v0.6.1
> 
> So basically everything worked fine when I removed "import { IRoot } from '../../plugins/cordova-plugin-iroot/iroot';" line from the app.component.ts and changed the line "declare var IRoot: IRoot;" to "declare var IRoot;".
> 
> Try this and everything works (for people who are trying to directly copy paste the code and getting errors)
> 
> Thanks @WuglyakBolgoink for the perfect code !

This is working. Thanks, bro
